apiVersion: app.kiegroup.org/v1beta1
kind: KogitoBuild
metadata:
  name: swf-greeting-persistence-monitoring
spec:
  type: RemoteSource
  #env:
  # env can be used to set variables during build
  #- name: MY_CUSTOM_ENV
  #  value: "my value"
  gitSource:
    contextDir: swf-greeting-persistence-monitoring
    uri: 'https://github.com/jesuino/quarkus-examples'
  # set your maven nexus repository to speed up the build time
  #mavenMirrorURL:
---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  name: swf-greeting-persistence-monitoring
  infra:
    - kogito-infinispan-infra
    - kogito-kafka-infra

